2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Configure stats pid to 165
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Loading settings from /content/openset_domain_adaptation/wandb/settings
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:_log_setup():524] Logging user logs to /content/openset_domain_adaptation/wandb/run-20231213_154032-u510u1kj/logs/debug.log
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:_log_setup():525] Logging internal logs to /content/openset_domain_adaptation/wandb/run-20231213_154032-u510u1kj/logs/debug-internal.log
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:init():564] calling init triggers
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:init():614] starting backend
2023-12-13 15:40:32,461 INFO    MainThread:165 [wandb_init.py:init():618] setting up manager
2023-12-13 15:40:32,465 INFO    MainThread:165 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-13 15:40:32,466 INFO    MainThread:165 [wandb_init.py:init():624] backend started and connected
2023-12-13 15:40:32,480 INFO    MainThread:165 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-13 15:40:37,493 INFO    MainThread:165 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-13 15:40:37,494 INFO    MainThread:165 [wandb_init.py:init():716] updated telemetry
2023-12-13 15:40:37,498 INFO    MainThread:165 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-13 15:42:07,568 ERROR   MainThread:165 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-12-13 15:42:07,585 ERROR   MainThread:165 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
